apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: web-application
spec:
  maxReplicas: 10
  minReplicas: 2
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: web-application
  targetCPUUtilizationPercentage: 20
