apiVersion: v1
kind: Pod
metadata:
  name: init-container-demo
spec:
  containers:
  - name: nginx
    image: nginx

    volumeMounts:
    - name: workdir
      mountPath: /usr/share/nginx/html

  initContainers:
  - name: busybox
    image: busybox

    command: ["/bin/sh"]
    args: ["-c", "echo '<html><h1>Hello, This Webpage was created by Init Container</h1><html>' >> /work-dir/index.html"]

    volumeMounts:
    - name: workdir
      mountPath: "/work-dir"

  volumes:
  - name: workdir
    emptyDir: {}
