apiVersion: v1
kind: Pod
metadata:
  name: web-server
spec:
  containers:
  - image: nginx
    name: web-container

    volumeMounts:
    - name: nfs-volume
      mountPath: /usr/share/nginx/html

  volumes:
  - name: nfs-volume
    persistentVolumeClaim:
      claimName: pvc1
