---
apiVersion: v1
kind: Pod
metadata:
  name: pod-1
spec:
  containers:
  - name: pod-1
    image: nginx
  nodeSelector:
    vip: "maybe"
---
apiVersion: v1
kind: Pod
metadata:
  name: pod-2
spec:
  containers:
  - name: pod-2
    image: nginx
  nodeSelector:
    vip: "maybe"
---
apiVersion: v1
kind: Pod
metadata:
  name: pod-3
spec:
  containers:
  - name: pod-3
    image: nginx
  nodeSelector:
    vip: "maybe"
