apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  replicas: 6
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      tolerations:
      - key: "myKey"
        operator: "Equal"
        value: "myValue"
        effect: "NoSchedule"
      containers:
      - name: web-container
        image: nginx
