apiVersion: v1
kind: Pod
metadata:
  name: c1
spec:
  containers:
  - name: prev-container
    image: busybox
    command: [ "sh", "-c", "sleep 1h" ]
    securityContext:
      allowPrivilegeEscalation: true
      privileged: true
